# Generated by Django 3.2.4 on 2021-08-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'ٌصورت حساب', 'verbose_name_plural': 'صورت حساب ها'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
