# Generated by Django 3.2.4 on 2021-08-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
        ('Payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='code_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_sale', to='Discount.code_discount'),
        ),
    ]
