# Generated by Django 3.2.4 on 2021-08-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='new_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
