# Generated by Django 3.2.4 on 2021-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
