# Generated by Django 3.2.4 on 2021-08-31 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_new_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='new_price',
        ),
    ]
