# Generated by Django 3.2.4 on 2021-08-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20210813_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
