# Generated by Django 3.2.4 on 2021-08-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0001_initial'),
        ('Books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cash_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_sale', to='Discount.percentage_discount'),
        ),
        migrations.AddField(
            model_name='book',
            name='percentage_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='percentage_sale', to='Discount.percentage_discount'),
        ),
    ]
