# Generated by Django 3.2.4 on 2021-08-23 11:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselected this instead of deleting.', verbose_name='Active status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('num_uses', models.IntegerField(default=0, verbose_name='Number of times already used')),
                ('active', models.BooleanField()),
                ('amount', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تخفیف نقدی',
                'verbose_name_plural': 'تخفیفات نقدی',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselected this instead of deleting.', verbose_name='Active status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('num_uses', models.IntegerField(default=0, verbose_name='Number of times already used')),
                ('active', models.BooleanField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'کد تخفیف ',
                'verbose_name_plural': 'کد های تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Percentage_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselected this instead of deleting.', verbose_name='Active status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation On')),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified On')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('num_uses', models.IntegerField(default=0, verbose_name='Number of times already used')),
                ('active', models.BooleanField()),
                ('percentage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تخفیف درصدی',
                'verbose_name_plural': 'تخفیفات درصدی',
            },
        ),
    ]
