# Generated by Django 3.2.4 on 2021-08-17 20:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminuser',
        ),
        migrations.DeleteModel(
            name='EmployeeProxy',
        ),
        migrations.CreateModel(
            name='Adminuser',
            fields=[
            ],
            options={
                'verbose_name': 'ادمین',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
